[linux_servers]
192.168.1.111 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
192.168.1.102 ansible_user=root  ansible_ssh_private_key_file=~/.ssh/id_rsa
192.168.1.100 ansible_user=admin  ansible_ssh_private_key_file=~/.ssh/id_rsa

[windows_servers]
192.168.1.210 ansible_user=Administrator ansible_password=YourPassword123 ansible_connection=winrm ansible_winrm_transport=basic 
192.168.1.200 ansible_user=admin ansible_password=SecurePass456 ansible_connection=winrm ansible_winrm_transport=basic
