all:
  hosts:

    localhost:
      ansible_connection: local
      ansible_user: lazrak
      loki_url: "http://localhost:3100/loki/api/v1/push"
      custom_log_paths:
        - /var/log/nginx/*.log
        - /app/logs/*.log
        - /var/log/myapp/*.log
  
    192.168.1.111:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      custom_log_paths:
        - /var/log/nginx/*.log
        - /app/logs/*.log
        - /var/log/myapp/*.log
        

  
  
    192.168.1.100:
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      custom_log_paths:
        - /var/lib/docker/containers/*/*-json.log
        - /home/admin/app/logs/*.log
    
    192.168.1.210:
      ansible_user: Administrator
      ansible_password: YourPassword123
      ansible_connection: winrm
      ansible_winrm_transport: basic
      custom_log_paths:
        - "C:\\iis\\logs\\*.log"
        - "C:\\MyApp\\logs\\*.log"
    
    192.168.1.200:
      ansible_user: admin
      ansible_password: SecurePass456
      ansible_connection: winrm
      ansible_winrm_transport: basic