- name: Include Linux tasks
  include_tasks: install_linux.yml
  when: ansible_os_family != "Windows"

- name: Include Windows tasks  
  include_tasks: install_windows.yml
  when: ansible_os_family == "Windows"

