grafana_agent_version: "v0.40.3"
loki_url: "http://localhost:3100/loki/api/v1/push"
log_path: "/var/log/*.log"  # Default value for Linux
log_path_windows: "C:\\Windows\\System32\\LogFiles\\*.log"  # Default value for Windows